#!/usr/bin/env node
/**
 * Regenerates per-plugin artifacts from core/ — the single source of truth.
 *
 *   node scripts/sync-core.mjs            write artifacts
 *   node scripts/sync-core.mjs --check    fail (exit 1) if any artifact is stale
 *
 * core/ holds the canonical knowledge-base templates and config schema. The
 * Claude Code plugin needs them as committed files (it ships self-contained);
 * the opencode plugin needs them as a TypeScript module to inline at build
 * time. Both outputs are committed so the repo is always buildable.
 *
 * Runs on Node or Bun — no dependencies.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join } from "node:path"

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..")
const check = process.argv.includes("--check")

const coreTemplatesDir = join(repoRoot, "core", "templates")
const ccPluginDir = join(repoRoot, "plugins", "lessons-learned")
const ocGeneratedDir = join(repoRoot, "plugins", "lessons-learned-opencode", "src", "generated")

/** Normalize to LF so CRLF checkouts don't produce false drift. */
const norm = (s) => s.replace(/\r\n/g, "\n")
const readCore = (relPath) => norm(readFileSync(join(repoRoot, "core", relPath), "utf8"))

/** Templates copied verbatim into the Claude Code plugin. */
const ccTemplates = ["index.md", "log.md", "schema.md", "readme.md", "page.md"]
/** Templates the opencode lesson-init tool writes — inlined as TS constants. */
const ocTemplates = {
  indexTemplate: "index.md",
  logTemplate: "log.md",
  schemaTemplate: "schema.md",
  readmeTemplate: "readme.md",
}

/** @type {{ path: string, content: string }[]} */
const outputs = []

// 1. Claude Code plugin: verbatim template copies.
for (const name of ccTemplates) {
  outputs.push({
    path: join(ccPluginDir, "templates", name),
    content: readCore(join("templates", name)),
  })
}

// 2. Claude Code plugin: verbatim config-schema copy.
outputs.push({
  path: join(ccPluginDir, "config-schema.json"),
  content: readCore("config-schema.json"),
})

// 3. opencode plugin: generated TypeScript module.
const escapeForTemplateLiteral = (s) =>
  s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${")

let ts =
  "// GENERATED by scripts/sync-core.mjs from core/templates/ — do not edit.\n" +
  "// Run `node scripts/sync-core.mjs` after changing a core/ template.\n\n"
for (const [constName, file] of Object.entries(ocTemplates)) {
  const body = escapeForTemplateLiteral(readCore(join("templates", file)))
  ts += `export const ${constName} = \`${body}\`\n\n`
}
outputs.push({ path: join(ocGeneratedDir, "templates.ts"), content: ts })

// Apply (write) or check (compare).
let drift = 0
for (const { path, content } of outputs) {
  let current = null
  try {
    current = norm(readFileSync(path, "utf8"))
  } catch {
    /* missing — counts as drift */
  }
  if (current === norm(content)) continue
  if (check) {
    console.error(`  drift: ${path}`)
    drift++
  } else {
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, content)
    console.log(`  wrote: ${path}`)
  }
}

if (check) {
  if (drift > 0) {
    console.error(`\n${drift} artifact(s) out of sync. Run: node scripts/sync-core.mjs`)
    process.exit(1)
  }
  console.log("core/ and generated artifacts are in sync.")
} else {
  console.log(`\nsync-core: ${outputs.length} artifact(s) written from core/.`)
}
